Traceback (most recent call last):
  File "1002_traceback_as_string.py", line 36, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
